# For details, see the GoReleaser documentation at http://goreleaser.com
project_name: synse-snmp-base
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -X github.com/vapor-ware/synse-sdk/sdk.BuildDate={{ .Date }}
      - -X github.com/vapor-ware/synse-sdk/sdk.GitCommit={{ .ShortCommit }}
      - -X github.com/vapor-ware/synse-sdk/sdk.GitTag={{ .Tag }}
      - -X github.com/vapor-ware/synse-sdk/sdk.GoVersion={{ .Env.GOLANG_VERSION }}
      - -X github.com/vapor-ware/synse-sdk/sdk.PluginVersion={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums-{{ .Tag }}.txt'
release:
  github:
    owner: vapor-ware
    name: synse-snmp-base
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^wip:'
      - '^deps:'
      - '^bump:'
      - '^typo:'
