version: '3'
services:
  snmp-emulator:
    image: vaporio/snmp-emulator:latest
    container_name: snmp-base-integration-emulator
    ports:
    - 1024:1024/udp
    command:
      - --data-dir=mibs/ups
      - --agent-udpv4-endpoint=0.0.0.0:1024
      - --v3-user=simulator
      - --v3-auth-key=auctoritas
      - --v3-auth-proto=SHA
      - --v3-priv-key=privatus
      - --v3-priv-proto=AES
