version: '3'
services:
  snmp-emulator:
    image: vaporio/snmp-emulator:latest
    container_name: snmp-base-integration-emulator
    ports:
    - 1024:1024/udp
    command: ['snmp_data/device/ups/pxgms_ups', '1024', '../dev/null', 'V3', 'authPriv', 'SHA', 'AES']
